/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.com.uricer.view;

import br.edu.com.uricer.dao.CartaoDAO;
import br.edu.com.uricer.dao.Conexao;
import br.edu.com.uricer.dao.DespesaDAO;
import br.edu.com.uricer.dao.ParcelaDAO;
import br.edu.com.uricer.dao.TagDAO;
import br.edu.com.uricer.dao.TipoDespesaDAO;
import br.edu.com.uricer.model.Cartao;
import br.edu.com.uricer.model.Despesa;
import br.edu.com.uricer.model.Parcela;
import br.edu.com.uricer.model.Tag;
import br.edu.com.uricer.model.TipoDespesa;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Correa
 */
public class AddDespesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddDespesa
     */
    public AddDespesa() {
        this.setTitle("DESPESA");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        initComponents();
        inicializar();
        listaComboBoxs();
    }

    private void inicializar(){
        Conexao con = new Conexao();
        despesaDAO = new DespesaDAO(con.getConexao());  
        tipoDespesaDAO = new TipoDespesaDAO(con.getConexao());
        tagDAO = new TagDAO(con.getConexao());
        cartaoDAO = new CartaoDAO(con.getConexao());
        parcelaDAO = new ParcelaDAO(con.getConexao());
        
        despesas = new ArrayList<>();
        despesaTableModel = new DespesaTableModel(despesas);
        TableDespesas.setModel(despesaTableModel);
        BotaoParcelas.setEnabled(false);
        BotaoExcluir.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JTabbedPane();
        PainelPesquisa = new javax.swing.JPanel();
        CampoPesquisar = new javax.swing.JTextField();
        BotaoPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDespesas = new javax.swing.JTable();
        PanelAdicionar = new javax.swing.JPanel();
        LabelId = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        LabelBanco = new javax.swing.JLabel();
        BotaoAddEditar = new javax.swing.JButton();
        CampoIdAdd = new javax.swing.JTextField();
        CampoDescricaoAdd = new javax.swing.JTextField();
        CampoLocalAdd = new javax.swing.JFormattedTextField();
        BotaoExcluir = new javax.swing.JButton();
        LabelBanco1 = new javax.swing.JLabel();
        ComboBoxPagamento = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxTag = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        CampoParcelasAdd = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        CampoValorAdd = new javax.swing.JFormattedTextField();
        ComboBoxCartao = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        CampoDataAdd = new javax.swing.JTextField();
        BotaoParcelas = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        BotaoPesquisar.setText("Pesquisar");
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText(" de um duplo click na linha referente a mesma.");

        jLabel1.setText("Para fazer uma edição/eliminação de alguma despesa,");

        TableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDespesas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDespesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDespesas);

        javax.swing.GroupLayout PainelPesquisaLayout = new javax.swing.GroupLayout(PainelPesquisa);
        PainelPesquisa.setLayout(PainelPesquisaLayout);
        PainelPesquisaLayout.setHorizontalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPesquisaLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(BotaoPesquisar))
                    .addComponent(jLabel1)
                    .addGroup(PainelPesquisaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPesquisaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)))
                .addContainerGap(237, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        PainelPesquisaLayout.setVerticalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        PainelPrincipal.addTab("Pesquisar", PainelPesquisa);

        LabelId.setText("Id:");

        LabelNome.setText("Descrição");

        LabelBanco.setText("Local:");

        BotaoAddEditar.setText("Adicionar/Editar Cartão");
        BotaoAddEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAddEditarActionPerformed(evt);
            }
        });

        CampoIdAdd.setEnabled(false);

        CampoLocalAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        CampoLocalAdd.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        LabelBanco1.setText("Pagamento em: ");

        jLabel4.setText("Cartão Usado:");

        jLabel5.setText("Tag: ");

        jLabel6.setText("Nº Parcelas:");

        CampoParcelasAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        CampoParcelasAdd.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel7.setText("Valor Total:");

        CampoValorAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        CampoValorAdd.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel8.setText("Data da compra: ");

        BotaoParcelas.setText("Exibir Parcelas");
        BotaoParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoParcelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdicionarLayout = new javax.swing.GroupLayout(PanelAdicionar);
        PanelAdicionar.setLayout(PanelAdicionarLayout);
        PanelAdicionarLayout.setHorizontalGroup(
            PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdicionarLayout.createSequentialGroup()
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelBanco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelBanco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CampoLocalAdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoDescricaoAdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxPagamento, 0, 97, Short.MAX_VALUE)
                            .addComponent(CampoIdAdd))
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdicionarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAdicionarLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(PanelAdicionarLayout.createSequentialGroup()
                                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ComboBoxTag, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CampoParcelasAdd)
                                            .addComponent(ComboBoxCartao, javax.swing.GroupLayout.Alignment.LEADING, 0, 395, Short.MAX_VALUE))
                                        .addGap(20, 20, 20))))
                            .addGroup(PanelAdicionarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(CampoValorAdd)
                                .addGap(20, 20, 20))))
                    .addGroup(PanelAdicionarLayout.createSequentialGroup()
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelAdicionarLayout.createSequentialGroup()
                                .addComponent(BotaoAddEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoExcluir))
                            .addGroup(PanelAdicionarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoDataAdd)
                                .addGap(33, 33, 33)))
                        .addComponent(BotaoParcelas)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelAdicionarLayout.setVerticalGroup(
            PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdicionarLayout.createSequentialGroup()
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelId)
                            .addComponent(CampoIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNome)
                            .addComponent(CampoDescricaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelBanco)
                            .addComponent(CampoLocalAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelBanco1)
                            .addComponent(ComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAdicionarLayout.createSequentialGroup()
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ComboBoxCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ComboBoxTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CampoParcelasAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CampoValorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CampoDataAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAddEditar)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoParcelas))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        PainelPrincipal.addTab("Adicionar/Editar", PanelAdicionar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        if(CampoIdAdd.getText() != null || !CampoIdAdd.getText().equals("")) {
            int resultado = JOptionPane.showConfirmDialog(this, "Confirma exclusão", "Confirmação", JOptionPane.YES_NO_CANCEL_OPTION);
            if(resultado == 0) {
                try {
                    int id = Integer.parseInt(CampoIdAdd.getText());
                    despesaDAO.deleteDespesa(id);
//                    limparEdits();
                } catch (SQLException ex) {
                    Logger.getLogger(AddCartao.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Erro ao excluir", "Erro", JOptionPane.ERROR);
                }
            }
        }
        limparEdits();
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoAddEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAddEditarActionPerformed
        // TODO add your handling code here:
        if(CampoDataAdd.getText().equals("") || CampoDescricaoAdd.getText().equals("") || CampoLocalAdd.getText().equals("") || CampoParcelasAdd.getText().equals("") || CampoValorAdd.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Favor Preencher todos os campos!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else{
            int idTipoDespesa = 0;
            int idCartao = 0;
            int idTag = 0;
            Tag tagObject = null;
            Cartao cartaoObject = null;
            TipoDespesa tipoObject = null;
            String descricao = CampoDescricaoAdd.getText();
            String local = CampoLocalAdd.getText();
            String tipoDespesa = ComboBoxPagamento.getSelectedItem().toString();
            String cartao = "Nenhum";
            String banco = " ";
            if(tipoDespesa.equals("Cartão")){
                cartao = ComboBoxCartao.getSelectedItem().toString();
                int pos = cartao.indexOf(" ");
                banco = cartao.substring((pos+3), cartao.length());
                cartao = cartao.substring(0, pos);
            }
            
            String tag = ComboBoxTag.getSelectedItem().toString();
            try {
                List<TipoDespesa> idTipoDespesas = tipoDespesaDAO.findByDescricaoTipoDespesa(tipoDespesa);
                if(idTipoDespesas.size() == 1){
                    for (Iterator<TipoDespesa> it = idTipoDespesas.iterator(); it.hasNext();) {
                        idTipoDespesa = it.next().getIdTipoDespesa();
                    }
                }
                List<Cartao> cartoes = cartaoDAO.findByNomeCartao(cartao, banco);
                if(cartoes.size() == 1){
                    for (Iterator<Cartao> it = cartoes.iterator(); it.hasNext();) {
                        idCartao = it.next().getIdCartao();
                    }
                }
                List<Tag> tags = tagDAO.findByCategoria(tag);
                if(tags.size() == 1){
                    for (Iterator<Tag> it = tags.iterator(); it.hasNext();) {
                        idTag = it.next().getIdTag();
                    }
                }

                tagObject = new Tag(tag);
                tagObject.setIdTag(idTag);
                cartaoObject = new Cartao(cartao, banco);
                cartaoObject.setIdCartao(idCartao);
                tipoObject = new TipoDespesa(tipoDespesa);
                tipoObject.setIdTipoDespesa(idTipoDespesa);

            } catch (SQLException ex) {
                Logger.getLogger(AddDespesa.class.getName()).log(Level.SEVERE, null, ex);
            }
            BigDecimal parcelas = new BigDecimal(CampoParcelasAdd.getText());
            BigDecimal valor = new BigDecimal(CampoValorAdd.getText());
            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = CampoDataAdd.getText();
            Date data = null;
            try {
                data = sdf.parse(dataFormatada);
            } catch (ParseException ex) {
                Logger.getLogger(AddReceita.class.getName()).log(Level.SEVERE, null, ex);
            }
            despesa = new Despesa(descricao, local, tipoObject, cartaoObject, tagObject, parcelas, valor, data);
            if(CampoIdAdd.getText() == null || CampoIdAdd.getText().equals("")) {
                Integer idCriado = 0;
                try {
                    idCriado = despesaDAO.createDespesa(despesa);
                } catch (SQLException ex) {
                    Logger.getLogger(AddCartao.class.getName()).log(Level.SEVERE, null, ex);
                }
                despesa.setIdDespesa(idCriado);
                CampoIdAdd.setText(idCriado.toString());

                try {
                    if(parcelas > BigDecimal(1.0){
                        
                        for(int i = 1; i <= parcelas; i++){
                            Parcela parcela = new Parcela(valor.divide(parcelas), idCriado, data);
                            parcelaDAO.createParcela(parcela);
                        }
                    } else{
                        Parcela parcela = new Parcela(valor, idCriado, data);
                        parcelaDAO.createParcela(parcela);
                    }
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(AddDespesa.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                try {
                    int id = Integer.parseInt(CampoIdAdd.getText());
                    despesa.setIdDespesa(id);
                    despesaDAO.updateDespesa(despesa);
                } catch (SQLException ex) {
                    Logger.getLogger(AddCartao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_BotaoAddEditarActionPerformed

    private void limparEdits(){
        CampoDataAdd.setText("");
        CampoDescricaoAdd.setText("");
        CampoPesquisar.setText("");
        CampoIdAdd.setText("");
        CampoLocalAdd.setText("");
        CampoParcelasAdd.setText("");
        CampoValorAdd.setText("");
    }
    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed
        // TODO add your handling code here:
        try{  
            despesas = despesaDAO.findByDescricao(CampoPesquisar.getText());        
            despesaTableModel.setDespesas(despesas);
            despesaTableModel.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(AddDespesa.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_BotaoPesquisarActionPerformed

    private void TableDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDespesasMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            despesa = despesas.get(TableDespesas.getSelectedRow());
            CampoIdAdd.setText(String.valueOf(despesa.getIdDespesa()));
            CampoDescricaoAdd.setText(despesa.getDescricaoDespesa());
            CampoLocalAdd.setText(despesa.getLocalDespesa());
            ComboBoxPagamento.setSelectedItem(despesa.getTipoDespesa().getDescricaoTipoDespesa());
            ComboBoxCartao.setSelectedItem(despesa.getFkCartaoUsado().getNomeCartao() + " - " + despesa.getFkCartaoUsado().getBanco());
            ComboBoxTag.setSelectedItem(despesa.getTag().getCategoria());
            CampoParcelasAdd.setText(String.valueOf(despesa.getNumeroParcela()));
            CampoValorAdd.setText(String.valueOf(despesa.getValorTotalDespesa()));
            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
            Date dataFormatada = despesa.getDataDespesa();
            CampoDataAdd.setText(sdf.format(dataFormatada));
            PainelPrincipal.setSelectedIndex(1);
            CampoDescricaoAdd.setEnabled(true);
            BotaoParcelas.setEnabled(true);
            BotaoExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_TableDespesasMouseClicked

    private void BotaoParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoParcelasActionPerformed
        try{            
            new ParcelasEdit(CampoIdAdd.getText()).setVisible(true);
        }catch (SQLException ex) {
            Logger.getLogger(AddDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoParcelasActionPerformed

    private void listaComboBoxs(){       
        try {
            List<TipoDespesa> tipoDespesas = tipoDespesaDAO.listar();
            for (TipoDespesa tipoDespesa : tipoDespesas) {
                ComboBoxPagamento.addItem(tipoDespesa.getDescricaoTipoDespesa());
            }
            List<Tag> tags = tagDAO.listar();
            for (Tag tag : tags) {
                ComboBoxTag.addItem(tag.getCategoria());
            }
            List<Cartao> cartoes = cartaoDAO.listar();
            for (Cartao cartao : cartoes) {
                ComboBoxCartao.addItem(cartao.getNomeCartao() + " - " + cartao.getBanco());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAddEditar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoParcelas;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JTextField CampoDataAdd;
    private javax.swing.JTextField CampoDescricaoAdd;
    private javax.swing.JTextField CampoIdAdd;
    private javax.swing.JFormattedTextField CampoLocalAdd;
    private javax.swing.JFormattedTextField CampoParcelasAdd;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JFormattedTextField CampoValorAdd;
    private javax.swing.JComboBox ComboBoxCartao;
    private javax.swing.JComboBox ComboBoxPagamento;
    private javax.swing.JComboBox ComboBoxTag;
    private javax.swing.JLabel LabelBanco;
    private javax.swing.JLabel LabelBanco1;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JPanel PainelPesquisa;
    private javax.swing.JTabbedPane PainelPrincipal;
    private javax.swing.JPanel PanelAdicionar;
    private javax.swing.JTable TableDespesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Despesa despesa;
    private DespesaDAO despesaDAO;
    private List<Despesa> despesas;
    private TipoDespesaDAO tipoDespesaDAO;
    private TagDAO tagDAO;
    private CartaoDAO cartaoDAO;
    private ParcelaDAO parcelaDAO;
    private DespesaTableModel despesaTableModel;
}
