/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.com.uricer.view;

import br.edu.com.uricer.dao.Conexao;
import br.edu.com.uricer.dao.ReceitaDAO;
import br.edu.com.uricer.model.Receita;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Correa
 */
public class AddReceita extends javax.swing.JInternalFrame {

    
    public AddReceita() {
        this.setTitle("RECEITA");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        initComponents();
        inicializar();
    }
    private void inicializar(){
        Conexao con = new Conexao();
        receitaDAO = new ReceitaDAO(con.getConexao());        
        
        receitas = new ArrayList<>();
        receitaTableModel = new ReceitaTableModel(receitas);
        TableReceita.setModel(receitaTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JTabbedPane();
        PainelPesquisar = new javax.swing.JPanel();
        LabelPesquisar = new javax.swing.JLabel();
        CampoPesquisar = new javax.swing.JTextField();
        BotaoPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReceita = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PainelAddEdit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotaoAdd = new javax.swing.JButton();
        CampoIdAdd = new javax.swing.JTextField();
        CampoDescricaoAdd = new javax.swing.JTextField();
        CampoValorAdd = new javax.swing.JFormattedTextField();
        CampoDataAdd = new javax.swing.JFormattedTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        LabelPesquisar.setText("Receita:");

        BotaoPesquisar.setText("Pesquisar");
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });

        TableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReceitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableReceita);

        jLabel5.setText("Para fazer uma edição/eliminação de alguma receita,");

        jLabel6.setText(" de um duplo click na linha referente ao mesmo.");

        javax.swing.GroupLayout PainelPesquisarLayout = new javax.swing.GroupLayout(PainelPesquisar);
        PainelPesquisar.setLayout(PainelPesquisarLayout);
        PainelPesquisarLayout.setHorizontalGroup(
            PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelPesquisarLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(PainelPesquisarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPesquisarLayout.createSequentialGroup()
                        .addComponent(LabelPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoPesquisar)
                        .addGap(37, 37, 37)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PainelPesquisarLayout.setVerticalGroup(
            PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPesquisar)
                    .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelPrincipal.addTab("Pesquisar", PainelPesquisar);

        jLabel1.setText("Id:");

        jLabel2.setText("Descrição: ");

        jLabel3.setText("Valor: ");

        jLabel4.setText("Data: ");

        BotaoAdd.setText("Adicionar Receita");
        BotaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAddActionPerformed(evt);
            }
        });

        CampoIdAdd.setEnabled(false);

        CampoDescricaoAdd.setNextFocusableComponent(CampoValorAdd);

        CampoValorAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        CampoValorAdd.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        CampoValorAdd.setNextFocusableComponent(CampoDataAdd);

        CampoDataAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        CampoDataAdd.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        CampoDataAdd.setNextFocusableComponent(BotaoAdd);

        javax.swing.GroupLayout PainelAddEditLayout = new javax.swing.GroupLayout(PainelAddEdit);
        PainelAddEdit.setLayout(PainelAddEditLayout);
        PainelAddEditLayout.setHorizontalGroup(
            PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoAdd)
                    .addGroup(PainelAddEditLayout.createSequentialGroup()
                        .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoIdAdd)
                            .addComponent(CampoValorAdd)
                            .addComponent(CampoDataAdd)
                            .addGroup(PainelAddEditLayout.createSequentialGroup()
                                .addComponent(CampoDescricaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(210, 210, 210))
        );
        PainelAddEditLayout.setVerticalGroup(
            PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoDescricaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoValorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoDataAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoAdd)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        PainelPrincipal.addTab("Adicionar", PainelAddEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAddActionPerformed
        // TODO add your handling code here:
        BigDecimal valor = new BigDecimal(CampoValorAdd.getText());
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = CampoDataAdd.getText();
        Date data = null;
        try {
            data = sdf.parse(dataFormatada);
        } catch (ParseException ex) {
            Logger.getLogger(AddReceita.class.getName()).log(Level.SEVERE, null, ex);
        }
        receita = new Receita(CampoDescricaoAdd.getText(), valor, data);
        if(CampoIdAdd.getText() == null || CampoIdAdd.getText().equals("")){
            
            try {
                Integer idCriado = receitaDAO.createReceita(receita);
                receita.setIdReceita(idCriado);
                CampoIdAdd.setText(idCriado.toString());
            } catch (SQLException ex) {
                Logger.getLogger(AddReceita.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
                try {
                    int id = Integer.parseInt(CampoIdAdd.getText());
                    receita.setIdReceita(id);
                    receitaDAO.updateAllReceita(receita);
                } catch (SQLException ex) {
                    Logger.getLogger(AddTag.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_BotaoAddActionPerformed

    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed
        // TODO add your handling code here:
        try {
            receitas = receitaDAO.findByDescricao(CampoPesquisar.getText());
            System.out.println("receitas: " + receitas);
            receitaTableModel.setReceitas(receitas);
            receitaTableModel.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(AddCartao.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_BotaoPesquisarActionPerformed

    private void TableReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReceitaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            receita = receitas.get(TableReceita.getSelectedRow());
            CampoIdAdd.setText(String.valueOf(receita.getIdReceita()));
            CampoDescricaoAdd.setText(receita.getDescricaoReceita());
            CampoValorAdd.setText(String.valueOf(receita.getValorReceita()));
            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
            Date dataFormatada = receita.getDataReceita();
            CampoDataAdd.setText(sdf.format(dataFormatada));
            PainelPrincipal.setSelectedIndex(1);
            CampoDescricaoAdd.setEnabled(true);
//            btNovo.setEnabled(false);
//            btGravar.setEnabled(true);
//            btCancelar.setEnabled(true);
//            btExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_TableReceitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdd;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JFormattedTextField CampoDataAdd;
    private javax.swing.JTextField CampoDescricaoAdd;
    private javax.swing.JTextField CampoIdAdd;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JFormattedTextField CampoValorAdd;
    private javax.swing.JLabel LabelPesquisar;
    private javax.swing.JPanel PainelAddEdit;
    private javax.swing.JPanel PainelPesquisar;
    private javax.swing.JTabbedPane PainelPrincipal;
    private javax.swing.JTable TableReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Receita receita;
    private ReceitaDAO receitaDAO;
    private List<Receita> receitas;
    private ReceitaTableModel receitaTableModel;
}
