package br.edu.com.uricer.view;

import br.edu.com.uricer.dao.Conexao;
import br.edu.com.uricer.dao.TagDAO;
import br.edu.com.uricer.model.Tag;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author marisa.richter
 */
public class AddTag extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddTag
     */
    public AddTag() {
        this.setTitle("TAG");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        initComponents();
        inicializar();
    }
    
    private void inicializar(){
        Conexao con = new Conexao();
        tagDAO = new TagDAO(con.getConexao());        
        
        tags = new ArrayList<>();
        tagTableModel = new TagTableModel(tags);
        tableTag.setModel(tagTableModel);
        BotaoExcluir.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JTabbedPane();
        PainelPesquisar = new javax.swing.JPanel();
        LabelCategoria = new javax.swing.JLabel();
        BotaoPesquisar = new javax.swing.JButton();
        CampoPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTag = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PainelAddEdit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoCategoria = new javax.swing.JTextField();
        CampoId = new javax.swing.JTextField();
        BotaoAddEdit = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tag");

        LabelCategoria.setText("Categoria: ");

        BotaoPesquisar.setText("Pesquisar");
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });

        tableTag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTagMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTag);

        jLabel1.setText("Para fazer uma edição/eliminação de alguma tag,");

        jLabel2.setText(" de um duplo click na linha referente a mesma.");

        javax.swing.GroupLayout PainelPesquisarLayout = new javax.swing.GroupLayout(PainelPesquisar);
        PainelPesquisar.setLayout(PainelPesquisarLayout);
        PainelPesquisarLayout.setHorizontalGroup(
            PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisarLayout.createSequentialGroup()
                .addGroup(PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPesquisarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LabelCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BotaoPesquisar))
                    .addGroup(PainelPesquisarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPesquisarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1)))
                    .addGroup(PainelPesquisarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelPesquisarLayout.setVerticalGroup(
            PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PainelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCategoria)
                    .addComponent(BotaoPesquisar)
                    .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        PainelPrincipal.addTab("Pesquisar", PainelPesquisar);

        jLabel3.setText("Id: ");

        jLabel4.setText("Categoria: ");

        CampoId.setEnabled(false);

        BotaoAddEdit.setText("Adicionar/Editar");
        BotaoAddEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAddEditActionPerformed(evt);
            }
        });

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAddEditLayout = new javax.swing.GroupLayout(PainelAddEdit);
        PainelAddEdit.setLayout(PainelAddEditLayout);
        PainelAddEditLayout.setHorizontalGroup(
            PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAddEditLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelAddEditLayout.createSequentialGroup()
                        .addComponent(BotaoAddEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoExcluir))
                    .addGroup(PainelAddEditLayout.createSequentialGroup()
                        .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoCategoria)
                            .addComponent(CampoId))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        PainelAddEditLayout.setVerticalGroup(
            PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAddEditLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAddEdit)
                    .addComponent(BotaoExcluir))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        PainelPrincipal.addTab("Adicionar/Editar", PainelAddEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAddEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAddEditActionPerformed
        // TODO add your handling code here:
        if(CampoCategoria.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Favor Preencher todos os campos!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else{
            String categoria = CampoCategoria.getText();
            tag = new Tag(categoria);
            if(CampoId.getText() == null || CampoId.getText().equals("")) {
                    Integer idCriado = 0;
                try {
                    idCriado = tagDAO.createTag(tag);
                } catch (SQLException ex) {
                    Logger.getLogger(AddTag.class.getName()).log(Level.SEVERE, null, ex);
                }
                    tag.setIdTag(idCriado);
                    CampoId.setText(idCriado.toString());

            }else {
                try {
                    int id = Integer.parseInt(CampoId.getText());
                    tag.setIdTag(id);
                    tagDAO.updateTag(tag);
                } catch (SQLException ex) {
                    Logger.getLogger(AddTag.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_BotaoAddEditActionPerformed

    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed
        // TODO add your handling code here:
        try {
            tags = tagDAO.findByCategoria(CampoPesquisar.getText());
            tagTableModel.setTags(tags);
            tagTableModel.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(AddTag.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_BotaoPesquisarActionPerformed

    private void tableTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTagMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            tag = tags.get(tableTag.getSelectedRow());
            CampoId.setText(String.valueOf(tag.getIdTag()));
            CampoCategoria.setText(tag.getCategoria());
            PainelPrincipal.setSelectedIndex(1);
            CampoCategoria.setEnabled(true);
            BotaoExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tableTagMouseClicked

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        if(CampoId.getText() != null || !CampoId.getText().equals("")) {
            int resultado = JOptionPane.showConfirmDialog(this, "Confirma exclusão", "Confirmação", JOptionPane.YES_NO_CANCEL_OPTION);
            if(resultado == 0) {
                try {
                    String categoria = CampoCategoria.getText();
                    int id = Integer.parseInt(CampoId.getText());
                    tag = new Tag(categoria);
                    tag.setIdTag(id);
                    tagDAO.deleteTag(tag);
                    limparEdits();
                } catch (SQLException ex) {
                    Logger.getLogger(AddTag.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Erro ao excluir", "Erro", JOptionPane.ERROR);
                }
            }
        }
    }//GEN-LAST:event_BotaoExcluirActionPerformed
    
    private void limparEdits(){
        CampoId.setText("");
        CampoCategoria.setText("");
        CampoPesquisar.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAddEdit;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JTextField CampoCategoria;
    private javax.swing.JTextField CampoId;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JPanel PainelAddEdit;
    private javax.swing.JPanel PainelPesquisar;
    private javax.swing.JTabbedPane PainelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTag;
    // End of variables declaration//GEN-END:variables
    private Tag tag;
    private TagDAO tagDAO;
    private List<Tag> tags;
    private TagTableModel tagTableModel;
}
