/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.com.uricer.view;

import br.edu.com.uricer.dao.CartaoDAO;
import br.edu.com.uricer.dao.Conexao;
import br.edu.com.uricer.dao.DespesaDAO;
import br.edu.com.uricer.model.Cartao;
import br.edu.com.uricer.model.Despesa;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Correa
 */
public class FaturaCartao extends javax.swing.JInternalFrame {

    /**
     * Creates new form FaturaCartao
     */
    public FaturaCartao() {
        this.setTitle("Fatura");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        
        initComponents();
        inicializar();
        listaComboBoxs();
    }
    
    private void inicializar(){
        Conexao con = new Conexao();
        cartaoDAO = new CartaoDAO(con.getConexao());  
        despesaDAO = new DespesaDAO(con.getConexao()); 
        
        despesas = new ArrayList<>();
        despesaTableModel = new DespesaTableModel(despesas);
        TableFatura.setModel(despesaTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFatura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxCartao = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxMes = new javax.swing.JComboBox();
        ComboBoxAno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        CampoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFatura = new javax.swing.JTable();
        BotaoFatura = new javax.swing.JButton();

        jLabel1.setText("Selecione o Cartão: ");

        jLabel2.setText("Selecione o mês e o ano: ");

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        ComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016" }));

        jLabel3.setText("Valor Total: ");

        TableFatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableFatura);

        BotaoFatura.setText("Emitir Fatura");
        BotaoFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFaturaLayout = new javax.swing.GroupLayout(PainelFatura);
        PainelFatura.setLayout(PainelFaturaLayout);
        PainelFaturaLayout.setHorizontalGroup(
            PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFaturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelFaturaLayout.createSequentialGroup()
                        .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxCartao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxMes, 0, 104, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoFatura)
                        .addGap(0, 188, Short.MAX_VALUE))))
            .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelFaturaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PainelFaturaLayout.setVerticalGroup(
            PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoFatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelFaturaLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFaturaActionPerformed
        // TODO add your handling code here:
        try {
            int idCartao = 0;
            String cartao = ComboBoxCartao.getSelectedItem().toString();
            int pos = cartao.indexOf(" ");
            String banco = cartao.substring((pos+3), cartao.length());
            cartao = cartao.substring(0, pos);
            cartoes = cartaoDAO.findByNomeCartao(cartao, banco);
            if(cartoes.size() == 1){
                for (Iterator<Cartao> it = cartoes.iterator(); it.hasNext();) {
                    idCartao = it.next().getIdCartao();
                }
            }
            int mes = Integer.parseInt(ComboBoxMes.getSelectedItem().toString());
            int ano = Integer.parseInt(ComboBoxAno.getSelectedItem().toString());
            despesas = despesaDAO.findFatura(idCartao, mes, ano);
            despesaTableModel.setDespesas(despesas);
            despesaTableModel.fireTableDataChanged();
            BigDecimal total = new BigDecimal(0.0);
            for (Despesa despesa : despesas) {
                total = total.add(despesa.getValorTotalDespesa());
            }
            CampoTotal.setText("R$ " + String.valueOf(total));
        } catch (SQLException ex) {
            Logger.getLogger(AddCartao.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_BotaoFaturaActionPerformed

    private void listaComboBoxs(){       
        try {
            List<Cartao> cartoesL = cartaoDAO.listar();
            for (Cartao cartao : cartoesL) {
                ComboBoxCartao.addItem(cartao.getNomeCartao() + " - " + cartao.getBanco());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FaturaCartao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFatura;
    private javax.swing.JTextField CampoTotal;
    private javax.swing.JComboBox ComboBoxAno;
    private javax.swing.JComboBox ComboBoxCartao;
    private javax.swing.JComboBox ComboBoxMes;
    private javax.swing.JPanel PainelFatura;
    private javax.swing.JTable TableFatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private List<Cartao> cartoes;
    private CartaoDAO cartaoDAO;
    private List<Despesa> despesas;
    private DespesaDAO despesaDAO;
    private DespesaTableModel despesaTableModel;
}
