/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.com.uricer.view;

import br.edu.com.uricer.dao.CartaoDAO;
import br.edu.com.uricer.dao.Conexao;
import br.edu.com.uricer.dao.DespesaDAO;
import br.edu.com.uricer.dao.ParcelaDAO;
import br.edu.com.uricer.dao.StatusDAO;
import br.edu.com.uricer.dao.TagDAO;
import br.edu.com.uricer.dao.TipoDespesaDAO;
import br.edu.com.uricer.model.Cartao;
import br.edu.com.uricer.model.Despesa;
import br.edu.com.uricer.model.Parcela;
import br.edu.com.uricer.model.StatusParcela;
import br.edu.com.uricer.model.Tag;
import br.edu.com.uricer.model.TipoDespesa;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Correa
 */
public class RelatorioDespesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FaturaCartao
     */
    public RelatorioDespesa() {
        this.setTitle("Relatório");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        
        initComponents();
        inicializar();
        listaComboBoxs();
    }
    
    private void inicializar(){
        Conexao con = new Conexao();
        tipoDespesaDAO = new TipoDespesaDAO(con.getConexao());  
        despesaDAO = new DespesaDAO(con.getConexao()); 
        tagDAO = new TagDAO(con.getConexao()); 
        statusDAO = new StatusDAO(con.getConexao());
        parcelaDAO = new ParcelaDAO(con.getConexao());
        
        despesas = new ArrayList();
        parcelas = new ArrayList();
        despesaTableModel = new RelatorioTableModel(despesas, parcelas);
        TableFatura.setModel(despesaTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFatura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxTag = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxMes = new javax.swing.JComboBox();
        ComboBoxAno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        CampoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFatura = new javax.swing.JTable();
        BotaoFatura = new javax.swing.JButton();
        ComboBoxPagamento = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxStatus = new javax.swing.JComboBox();

        jLabel1.setText("Selecione a Categoria: ");

        jLabel2.setText("Selecione o mês e o ano: ");

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        ComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016" }));

        jLabel3.setText("Valor Total: ");

        TableFatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableFatura);

        BotaoFatura.setText("Emitir Relatório");
        BotaoFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFaturaActionPerformed(evt);
            }
        });

        jLabel4.setText("Selecione o Tipo de Pagamento: ");

        jLabel5.setText("Selecione o Status: ");

        javax.swing.GroupLayout PainelFaturaLayout = new javax.swing.GroupLayout(PainelFatura);
        PainelFatura.setLayout(PainelFaturaLayout);
        PainelFaturaLayout.setHorizontalGroup(
            PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFaturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(PainelFaturaLayout.createSequentialGroup()
                        .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelFaturaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(ComboBoxTag, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelFaturaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoFatura)))
                        .addContainerGap())
                    .addGroup(PainelFaturaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelFaturaLayout.setVerticalGroup(
            PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoFatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFaturaActionPerformed
        // TODO add your handling code here:
        try {
            int idTipoDespesa = 0;
            tag = tagDAO.findCategoria(ComboBoxTag.getSelectedItem().toString());
            tiposDespesa = tipoDespesaDAO.findByDescricaoTipoDespesa(ComboBoxPagamento.getSelectedItem().toString());
            if(tiposDespesa.size() == 1){
                for (Iterator<TipoDespesa> it = tiposDespesa.iterator(); it.hasNext();) {
                    idTipoDespesa = it.next().getIdTipoDespesa();
                }
            }
            status = statusDAO.findByStatus(ComboBoxStatus.getSelectedItem().toString());
            int mes = Integer.parseInt(ComboBoxMes.getSelectedItem().toString());
            int ano = Integer.parseInt(ComboBoxAno.getSelectedItem().toString());
            despesas = despesaDAO.findRelatorio(idTipoDespesa, tag.getIdTag(), status.getIdStatus(), mes, ano);
            parcelas = parcelaDAO.findParcelasRelatorio(idTipoDespesa, tag.getIdTag(), status.getIdStatus(), mes, ano);
            despesaTableModel.setDespesas(despesas);
            despesaTableModel.setParcelas(parcelas);
            despesaTableModel.fireTableDataChanged();
            BigDecimal total = new BigDecimal(0.0);
            for (Despesa despesa : despesas) {
                total = total.add(despesa.getValorTotalDespesa());
            }
            CampoTotal.setText("R$ " + String.valueOf(total));
        } catch (SQLException ex) {
            Logger.getLogger(AddCartao.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_BotaoFaturaActionPerformed

    private void listaComboBoxs(){       
        try {
            List<Tag> tagList = tagDAO.listar();
            for (Tag tag : tagList) {
                ComboBoxTag.addItem(tag.getCategoria());
            }
            List<TipoDespesa> tipoList = tipoDespesaDAO.listar();
            for (TipoDespesa tipoDespesa : tipoList) {
                ComboBoxPagamento.addItem(tipoDespesa.getDescricaoTipoDespesa());
            }
            List<StatusParcela> status = statusDAO.listar();
            for (StatusParcela statusList : status) {
                ComboBoxStatus.addItem(statusList.getStatusParcela());
            }
        } catch (SQLException ex) {
            Logger.getLogger(RelatorioDespesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFatura;
    private javax.swing.JTextField CampoTotal;
    private javax.swing.JComboBox ComboBoxAno;
    private javax.swing.JComboBox ComboBoxMes;
    private javax.swing.JComboBox ComboBoxPagamento;
    private javax.swing.JComboBox ComboBoxStatus;
    private javax.swing.JComboBox ComboBoxTag;
    private javax.swing.JPanel PainelFatura;
    private javax.swing.JTable TableFatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private List<TipoDespesa> tiposDespesa;
    private TipoDespesaDAO tipoDespesaDAO;
    private List<Tag> tags;
    private Tag tag;
    private TagDAO tagDAO;
    private StatusParcela status;
    private StatusDAO statusDAO;
    private ParcelaDAO parcelaDAO;
    private Parcela parcela;
    private List<Parcela> parcelas;
    private List<Despesa> despesas;
    private DespesaDAO despesaDAO;
    private RelatorioTableModel despesaTableModel;
}
