/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.com.uricer.view;

import java.util.Locale;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Correa
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        initComponents();
        InternalFrame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        InternalFrame = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        AdicionarMenu = new javax.swing.JMenu();
        ReceitaMenu = new javax.swing.JMenuItem();
        DespesaMenu = new javax.swing.JMenuItem();
        CartaoMenu = new javax.swing.JMenuItem();
        TagMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        FaturaMenu = new javax.swing.JMenuItem();
        RelatorioDespesaMenu = new javax.swing.JMenuItem();
        ProximosPagamentosMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("tete");

        jDesktopPane1.setLayout(new javax.swing.OverlayLayout(jDesktopPane1));

        InternalFrame.setVisible(true);

        javax.swing.GroupLayout InternalFrameLayout = new javax.swing.GroupLayout(InternalFrame.getContentPane());
        InternalFrame.getContentPane().setLayout(InternalFrameLayout);
        InternalFrameLayout.setHorizontalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        InternalFrameLayout.setVerticalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jDesktopPane1.add(InternalFrame);

        AdicionarMenu.setText("Adicionar");

        ReceitaMenu.setText("Receita");
        ReceitaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceitaMenuActionPerformed(evt);
            }
        });
        AdicionarMenu.add(ReceitaMenu);

        DespesaMenu.setText("Despesa");
        DespesaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespesaMenuActionPerformed(evt);
            }
        });
        AdicionarMenu.add(DespesaMenu);

        CartaoMenu.setText("Cartão");
        CartaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartaoMenuActionPerformed(evt);
            }
        });
        AdicionarMenu.add(CartaoMenu);

        TagMenu.setText("Tag");
        TagMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TagMenuActionPerformed(evt);
            }
        });
        AdicionarMenu.add(TagMenu);

        jMenuBar1.add(AdicionarMenu);

        jMenu2.setText("Emitir");

        FaturaMenu.setText("Fatura do Cartao");
        jMenu2.add(FaturaMenu);

        RelatorioDespesaMenu.setText("Relatorio de Despesas");
        jMenu2.add(RelatorioDespesaMenu);

        ProximosPagamentosMenu.setText("Próximos pagamentos");
        jMenu2.add(ProximosPagamentosMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReceitaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceitaMenuActionPerformed
        // TODO add your handling code here:
        JInternalFrame addReceita = new JInternalFrame();
        addReceita = new AddReceita();
        addReceita.setVisible(true);
        jDesktopPane1.add(addReceita);
    }//GEN-LAST:event_ReceitaMenuActionPerformed

    private void CartaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartaoMenuActionPerformed
        // TODO add your handling code here:
        JInternalFrame addCartao = new JInternalFrame();
        addCartao = new AddCartao();
        addCartao.setVisible(true);
        jDesktopPane1.add(addCartao);
    }//GEN-LAST:event_CartaoMenuActionPerformed

    private void TagMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TagMenuActionPerformed
        // TODO add your handling code here:
        JInternalFrame addTag = new JInternalFrame();
        addTag = new AddTag();
        addTag.setVisible(true);
        jDesktopPane1.add(addTag);
        
    }//GEN-LAST:event_TagMenuActionPerformed

    private void DespesaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespesaMenuActionPerformed
        // TODO add your handling code here:
        JInternalFrame addDespesa = new JInternalFrame();
        addDespesa = new AddDespesa();
        addDespesa.setVisible(true);
        jDesktopPane1.add(addDespesa);
    }//GEN-LAST:event_DespesaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdicionarMenu;
    private javax.swing.JMenuItem CartaoMenu;
    private javax.swing.JMenuItem DespesaMenu;
    private javax.swing.JMenuItem FaturaMenu;
    private javax.swing.JInternalFrame InternalFrame;
    private javax.swing.JMenuItem ProximosPagamentosMenu;
    private javax.swing.JMenuItem ReceitaMenu;
    private javax.swing.JMenuItem RelatorioDespesaMenu;
    private javax.swing.JMenuItem TagMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    JDesktopPane deskPanel = new JDesktopPane();
}

